name: CI
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]
  release:
    types: [published]
jobs:
  build2021:
    name: Build and Test (Scala 2021)
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'pomadchin/advent-of-code'
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [11]
        distribution: [temurin]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Check formatting
        run: cd 2021/scala; sbt scalafmtCheckAll

      - name: Build project
        run: cd 2021/scala; sbt test
